#%RAML 0.8
title: social-scoreboard
baseUri: http://socialscoreboard-dawzayas.rhcloud.com/
version: 1

schemas:
  - score: !include social-scoreboard-score.schema
  - teamScore: !include social-scoreboard-team-score.schema
      
traits:
  - security:
      headers:
        Authorization:
          description: |
            Used to send a valid JWTtoken.
          example: jwt token
      responses:
        401:
          description: |
            No valid token found
          body:
            test/plain:
              example: "Unauthorized"
  - item-not-found:
      responses:
        500:
          description: |
            <<resourcePathName>> does not exists or invalid <<resourcePathName>>Id
          body:
            test/plain:
              example: "Error: Error: scoreId not exists"
  - valid-item-response:
      responses:
        200:
          body:
            application/json:
              schema: <<resourcePathName>>
              example: <<exampleItem>>
resourceTypes:
  - collection:
      description: Collection of all <<resourcePathName|!pluralize>> in Social Scoreboard
      is: [
        security
      ]
      get:
        description: Get a list of <<resourcePathName|!pluralize>>.
        responses:
          200:
            body:
              application/json:
                schema: <<resourcePathName>>
                example: <<exampleCollection>>
      post:
        is: [
          valid-item-response: {exampleItem: <<exampleItem>>}
        ]
  - collection-item:
      description: Entity representing a <<resourcePathName>>
      is: [
        security,
        item-not-found
      ]
      get:
        description: |
          Get the <<resourcePathName>>
          with <<resourcePathName>>Id =
          {<<resourcePathName>>Id}
        is: [
          valid-item-response: {exampleItem: <<exampleItem>>}
        ]
      delete:
        responses:
          200:
            body:
              test/plain:
                example: "Score[<<resourcePathName>>Id] deleted"
/score:
  type:
    collection:
      exampleCollection: !include social-scoreboard-scores.sample
      exampleItem: !include social-scoreboard-score.sample
  /{scoreId}:
      type:
        collection-item:
          exampleItem: !include social-scoreboard-score.sample